#https://github.com/pages-themes/midnight#usage
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Aloo
description: Open source project that provides a proxy layer between a docker registry and an end user. It allows users to manage access rights and permissions for different docker images and repositories.
show_downloads: false
